name: qa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - biopandas
  - click
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - prody
  - scikit-learn
  - scipy
  - seaborn
