name: qa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - black
  - biopandas
  - cookiecutter
  - flake8
  - git
  - matplotlib
  - mypy
  - numpy
  - pandas
  - pip
  - pydantic
  - pytest
  - pytest-cov
  - scikit-learn
  - scipy
  - seaborn
  - sphinx-autoapi
  - sphinx_rtd_theme
  - ambertools
  - pip:
    - https://github.com/revitron/revitron-sphinx-theme/archive/master.zip