name: qa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - biopandas
  - biopython
  - matplotlib
  - mdanalaysis
  - numpy
  - pandas
  - pip
  - scikit-learn
  - scipy
  - seaborn
