
conda install numpy

conda install -c conda-forge scipy
conda install -c conda-forge 
conda install -c conda-forge pytest
conda install -c conda-forge pydantic
pip install pytest-cov
pip install sphinx sphinx_rtd_theme
pip install https://github.com/revitron/revitron-sphinx-theme/archive/master.zip

name: qa
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - cookiecutter
  - flake8
  - git
  - matplotlib
  - mypy
  -
  -

  - pandas

  - pip
  - pip:
    - git+https://github.com/blaze/dask.git#egg=dask[complete]